### ISSUE TITLE
运行一段时间之后报错，程序退出

### ISSUE THREAD

**Issue by xbox1994** [neoql/btlet#5]
```
Have already sniff 194058 torrents.panic: interface conversion: interface {} is string, not int64

goroutine 396122512 [running]:
github.com/neoql/btlet.loadMeta(0xc42122fcb0, 0xc421f863c0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/neoql/btlet/sniffer.go:126 +0x557
github.com/neoql/btlet.(*Sniffer).Sniff.func1(0xc421f863c0, 0x14, 0xc4249e684c, 0x10, 0x10, 0x6f25)
	/root/go/src/github.com/neoql/btlet/sniffer.go:92 +0x1d8
github.com/neoql/btlet/dht.(*sybilTransaction).OnQuery(0xc4200746e0, 0x7e84c0, 0xc4200ecb40, 0xc4224209c0, 0xc4219baa5c, 0x4, 0xc4219baa40, 0xd, 0xc421f080c0, 0xb4, ...)
	/root/go/src/github.com/neoql/btlet/dht/crawler.go:254 +0xe4
github.com/neoql/btlet/dht.(*sybilMessageDisposer).DisposeQuery(0xc4200ecc00, 0xc4224209c0, 0xc4219baa5c, 0x4, 0xc4219baa40, 0xd, 0xc421f080c0, 0xb4, 0xc0, 0x0, ...)
	/root/go/src/github.com/neoql/btlet/dht/crawler.go:81 +0xa6
created by github.com/neoql/btlet/dht.newDisposerProxy.func1
	/root/go/src/github.com/neoql/btlet/dht/dht.go:169 +0xaa
exit status 2
```

看起来像是length出现string这样的特殊情况导致转换失败，应该需要加一个类型判断吧

**Comment by neoql** [comment]
@xbox1994 新版本把bt包重构了，现在应该没这个bug了

**Comment by xbox1994** [comment]
更新到了最新版本，新问题如下：
```
Have already sniff 203635 torrents.panic: reflect: reflect.Value.SetUint using unaddressable value

goroutine 106836704 [running]:
reflect.flag.mustBeAssignable(0x88)
	/usr/lib/go-1.10/src/reflect/value.go:234 +0x15c
reflect.Value.SetUint(0x71fc80, 0xc422c1e72b, 0x88, 0x5)
	/usr/lib/go-1.10/src/reflect/value.go:1521 +0x2f
github.com/neoql/btlet/bencode.(*Decoder).decodeInt(0xc4219f9b90, 0x71fc80, 0xc422c1e72b, 0x88, 0x71fc80, 0xc425838bc8)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:187 +0x402
github.com/neoql/btlet/bencode.(*Decoder).decode(0xc4219f9b90, 0x71fc80, 0xc422c1e72b, 0x88, 0xc424f4e5b0, 0x98)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:136 +0x631
github.com/neoql/btlet/bencode.(*Decoder).decodeDict(0xc4219f9b90, 0x73f1e0, 0xc42334d8b8, 0x195, 0x0, 0x0)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:401 +0x3a4
github.com/neoql/btlet/bencode.(*Decoder).decode(0xc4219f9b90, 0x711c40, 0xc42334d8b8, 0x16, 0x16, 0x0)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:142 +0x518
github.com/neoql/btlet/bencode.(*Decoder).Decode(0xc4219f9b90, 0x711c40, 0xc42334d8b8, 0xc424a25000, 0x1000)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:55 +0x15c
github.com/neoql/btlet/bencode.Unmarshal(0xc4254a4480, 0x52, 0x60, 0x711c40, 0xc42334d8b8, 0x1, 0x0)
	/root/go/src/github.com/neoql/btlet/bencode/docode.go:22 +0x1cb
github.com/neoql/btlet/bt.(*ExtCenter).HandlePayload(0xc42334d8a0, 0xc422a88701, 0xb5, 0x36b, 0xc422979fc0, 0x0, 0x0)
	/root/go/src/github.com/neoql/btlet/bt/extension.go:89 +0x3b3
github.com/neoql/btlet.(*Sniffer).afterCrawl(0xc42012e2a0, 0xc421b67a60, 0x14, 0xc4260aeb8c, 0x10, 0x10, 0x49d2)
	/root/go/src/github.com/neoql/btlet/sniffer.go:137 +0x5cb
github.com/neoql/btlet.(*Sniffer).(github.com/neoql/btlet.afterCrawl)-fm(0xc421b67a60, 0x14, 0xc4260aeb8c, 0x10, 0x10, 0x49d2)
	/root/go/src/github.com/neoql/btlet/sniffer.go:78 +0x66
github.com/neoql/btlet/dht.(*sybilTransaction).OnQuery(0xc420074690, 0x7ebb20, 0xc4200ecac0, 0xc4215eba70, 0xc42429a380, 0x8, 0xc42429a360, 0xd, 0xc42189a8c0, 0x6a, ...)
	/root/go/src/github.com/neoql/btlet/dht/crawler.go:254 +0xe4
github.com/neoql/btlet/dht.(*sybilMessageDisposer).DisposeQuery(0xc4200ecb80, 0xc4215eba70, 0xc42429a380, 0x8, 0xc42429a360, 0xd, 0xc42189a8c0, 0x6a, 0x70, 0x0, ...)
	/root/go/src/github.com/neoql/btlet/dht/crawler.go:81 +0xa6
created by github.com/neoql/btlet/dht.newDisposerProxy.func1
	/root/go/src/github.com/neoql/btlet/dht/dht.go:169 +0xaa
exit status 2
```

**Comment by fslove** [comment]
@xbox1994 新版本主要改变应该是bencode重构了,你可以看看作者提交的commit,目前bencode应该还没重构完成,很多转换代码都是临时测试的,还没开始优化,期待作者发布新的版本吧

**Comment by neoql** [comment]
@xbox1994 已经解决这个原因导致的退出了。是因为之前的bencode包在decode dict类型时，如果碰到两个相同的key就会panic。但是可能还会出现其他原因的退出，所以这个issue暂时不会close
